import Link from "next/link";
import "../globals.css";
import data from "./data";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <div>
      <div>
        {data.map((item, index) => (
          <div
            key={index}
            style={{ display: "inline-block", marginRight: "10px" }}
          >
            <Link href={item.url}>{item.name}</Link>
          </div>
        ))}
        {children}
      </div>
    </div>
  );
}
